public class Calculator {
    
    public void sumNum(integer a, integer b)//sum of 2 num
    {
        System.debug('Sum of two num is '+(a+b));
        
    }
    public void subNum(integer a, integer b)
    {
       System.debug('sub of two num is '+(a-b));  
       
    }
    public void mulNum(integer a, integer b)
    {
       System.debug('product of two num is '+(a*b));
    }
    public void divNum(integer a, integer b)
    {
       System.debug('div of two num is '+(a/b));
       
    }
}